#!/bin/sh
set -e
# $1 is "remove" or "purge"; only remove module on purge to be polite
if [ "$1" = "purge" ]; then
  if command -v selinuxenabled >/dev/null 2>&1 && selinuxenabled; then
    if command -v semodule >/dev/null 2>&1; then
      semodule -r himmelblaud || true
    fi
  fi
fi
exit 0
