#!/bin/bash

set -e

# Apply the patch that allows pam_himmelblau to r/w the himmelblaud socket
patch -F 2 /etc/apparmor.d/unix-chkpwd << 'EOF'
--- /etc/apparmor.d/unix-chkpwd	2024-10-07 13:41:33.143303700 -0600
+++ /etc/apparmor.d/unix-chkpwd	2024-10-07 13:36:55.740827834 -0600
@@ -11,7 +11,7 @@
 
 include <tunables/global>
 
-profile unix-chkpwd /{,usr/}{,s}bin/unix_chkpwd {
+profile unix-chkpwd /{,usr/}{,s}bin/unix_chkpwd flags=(attach_disconnected) {
   include <abstractions/base>
   include <abstractions/nameservice>
 
EOF

# Reload the AppArmor profile to apply the changes
sudo apparmor_parser -r /etc/apparmor.d/unix-chkpwd
