#!/usr/bin/env python3
"""
Himmelblau Dockerfile generator

Usage:
  python gen_dockerfiles.py [--out ./dockerfiles] [--only debian12,ubuntu22.04] [--arch amd64|arm64]

This follows a config-driven pattern inspired by Samba's bootstrap/config.py:
- deb family => cargo deb chain with per-package feature flags and --deb-revision=<distro>
- rpm/zypper family => cargo build + strip + cargo generate-rpm chain
- ebuild family => generates Gentoo ebuild file via gen_ebuild.py
- arch family => makepkg via scripts/package_arch.py (platform/arch/PKGBUILD)
"""

import argparse
import os
from pathlib import Path

# Architecture mapping
ARCH_MAP = {
    "amd64": {"docker_platform": "linux/amd64", "rpm_arch": "x86_64", "deb_arch": "amd64", "rust_target": "x86_64-unknown-linux-gnu"},
    "arm64": {"docker_platform": "linux/arm64", "rpm_arch": "aarch64", "deb_arch": "arm64", "rust_target": "aarch64-unknown-linux-gnu"},
}

GENERATED_MARKER = """\
#
# This file is generated by gen_dockerfiles.py
# Do not edit by hand — update the generator or config instead.
#

"""

# ---- Package config ----------------------------------------------------------

COMMON = [
    "git",
    "curl",
    "wget",
    "make",
    "pkg-config",
    "jq",
    "ca-certificates",
    "libtool",
    "autoconf",
    "gettext",
    "checkpolicy",
    "policycoreutils",
    "python3",
    "systemd",
]

PKG_PAIRS = [
    ("build-essential", "@development-tools"),
    ("gcc", "gcc"),
    ("g++", "gcc-c++"),
    ("libssl-dev", "openssl-devel"),
    ("libdbus-1-dev", "dbus-devel"),
    ("libkrb5-dev", "krb5-devel"),
    ("libpam0g-dev", "pam-devel"),
    ("libcap-dev", "libcap-devel"),
    ("libudev-dev", "libudev-devel"),
    ("cmake", "cmake"),
    ("libtss2-dev tpm-udev", "tpm2-tss-devel"),
    ("libclang-dev", "clang"),
    ("libpcre2-dev", "pcre2-devel"),
    ("libsqlite3-dev", "sqlite-devel"),
    ("libunistring-dev", "libunistring-devel"),
]

SELINUX_PKGS = ["policycoreutils-devel", "selinux-policy-targeted"]
AUTHSELECT_PKGS = ["authselect"]

DEB_PKGS = COMMON + [p for p, _ in PKG_PAIRS if p]
RPM_PKGS = COMMON + AUTHSELECT_PKGS + [q for _, q in PKG_PAIRS if q]

# enable caching of apt packages: https://docs.docker.com/build/cache/optimize/#use-cache-mounts
APT_BOOTSTRAP = """\
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \n
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt,sharing=locked \\
    apt-get update && apt-get install -y \\\n    {pkgs} \\\n && rm -rf /var/lib/apt/lists/*\n"""

DNF_BOOTSTRAP = """\
RUN dnf -y update && dnf -y install \\\n    {pkgs} \\\n && dnf clean all\n"""

ZYPPER_BOOTSTRAP = """\
RUN zypper --non-interactive refresh && \\\n    zypper --non-interactive update && \\\n    zypper --non-interactive install --no-recommends \\\n        {pkgs} && \\\n    zypper clean --all\n"""

PACMAN_BOOTSTRAP = """\
RUN pacman -Syu --noconfirm && \\\n    pacman -S --noconfirm --needed \\\n        {pkgs} && \\\n    pacman -Scc --noconfirm\n"""

ARCH_PKGS = [
    "base-devel",
    "clang",
    "cmake",
    "dbus",
    "gettext",
    "git",
    "krb5",
    "libcap",
    "libunistring",
    "openssl",
    "pam",
    "pcre2",
    "python",
    "rust",
    "sqlite",
    "systemd",
    "tpm2-tss",
]

FAMILIES = {
    "deb": {
        "bootstrap": APT_BOOTSTRAP,
        "pkgs": DEB_PKGS,
        "env": "ENV DEBIAN_FRONTEND=noninteractive HIMMELBLAU_ALLOW_MISSING_SELINUX=1",
    },
    "rpm": {
        "bootstrap": DNF_BOOTSTRAP,
        "pkgs": RPM_PKGS,
        "env": None,
    },
    "zypper": {
        "bootstrap": ZYPPER_BOOTSTRAP,
        "pkgs": RPM_PKGS,
        "env": None,
    },
    "ebuild": {
        # Minimal bootstrap for ebuild generation - just needs Python (in base image)
        "bootstrap": "# No additional packages needed - Python is in the base image",
        "pkgs": [],
        "env": None,
    },
    "arch": {
        "bootstrap": PACMAN_BOOTSTRAP,
        "pkgs": ARCH_PKGS,
        "env": None,
    },
}

# ---- Final command builders --------------------------------------------------

PACKAGES = [
    # (crate name, crate source, needs_tpm_feature)
    # Only himmelblaud (src/daemon) and src/common define a tpm feature.
    # All other crates have no [features] section — passing --features tpm
    # to them causes a build error.
    ("himmelblaud", "src/daemon", True),
    ("nss_himmelblau", "src/nss", False),
    ("pam_himmelblau", "src/pam", False),
    ("sshd-config", "src/sshd-config", False),
    ("broker", "src/broker", False),
    ("sso", "src/sso", False),
    ("sso-policies", "src/sso-policies", False),
    ("qr-greeter", "src/qr-greeter", False),
    ("selinux", "src/selinux", False),
    ("apparmor", "src/apparmor", False),
    ("o365", "src/o365", False),
    ("himmelblau-orchestrator", "src/orchestrator", False),
]

CMD_TAB = "     "
CMD_SEP = f" && \\ \n{CMD_TAB}"


GEN_MANPAGE = "python3 src/common/scripts/gen_param_code.py --gen-man --man-output man/man5/himmelblau.conf.5"


def build_deb_final_cmd(features: list, distro_slug: str, cross_target: str = "") -> str:
    target_arg = f" --target={cross_target}" if cross_target else ""
    parts = []
    for pkg, _, needs_tpm in PACKAGES:
        if pkg == "selinux":
            continue
        pkg_features = list(features)
        if not needs_tpm:
            pkg_features = [f for f in pkg_features if f != "tpm"]
        feat_str = f" --features {','.join(pkg_features)}" if pkg_features else ""
        if "pam" in pkg or "nss" in pkg:
            feat_str += " --multiarch=same"
        cmd = f"cargo deb ${{CARGO_PATCH_ARG}}{target_arg}{feat_str} --deb-revision={distro_slug}${{DEB_REVISION_APPEND}} -p {pkg}"
        if pkg == "apparmor":
            package_dir = f"target/{cross_target}/debian" if cross_target else "target/debian"
            cmd += f" && python3 scripts/patch_apparmor_deb_relationships.py --distro={distro_slug} --package-dir={package_dir}"
        parts.append(cmd)
    gen_servicefiles = "make deb-servicefiles"
    return f'CMD ["/bin/sh", "-c", \\\n{CMD_TAB}"{GEN_MANPAGE} && {gen_servicefiles} && {CMD_SEP.join(parts)} "]'


def build_rpm_final_cmd(features: list, selinux: bool, apparmor: bool) -> str:
    feat_str = f" --features {','.join(features)}" if features else ""
    build = f"cargo build ${{CARGO_PATCH_ARG}} --release{feat_str} && \\ \n{CMD_TAB}"
    strip = CMD_SEP.join(["strip -s target/release/%s" % s for s in ["*.so", "aad-tool", "himmelblaud", "himmelblaud_tasks", "broker", "himmelblaud-orchestrator"]])
    pkgs = []
    for pkg in PACKAGES:
        if pkg[0] == "selinux" and not selinux:
            continue
        if pkg[0] == "apparmor" and not apparmor:
            continue
        pkgs.append(pkg)
    rpm_cmds = []
    for _, s, _ in pkgs:
        rpm_cmds.append(f"cargo generate-rpm -p {s}")
    rpms = CMD_SEP.join(rpm_cmds)
    gen_servicefiles = "make rpm-servicefiles ORCHESTRATOR_APPARMOR_PROFILE=himmelblau-orchestrator-container" if apparmor else "make rpm-servicefiles"
    gen_authselect = "(authselect select minimal --force || authselect select local --force) && make authselect"
    return f'CMD ["/bin/sh", "-c", \\\n{CMD_TAB}"{GEN_MANPAGE} && {gen_servicefiles} && {build}{strip} && {gen_authselect} && \\\n{CMD_TAB}{rpms}"]'


def build_gentoo_final_cmd(features: list, repo_root: Path) -> str:
    return f'CMD ["/bin/sh", "-c", "{GEN_MANPAGE} && python3 scripts/gen_ebuild.py --out ./packaging/"]'


def build_arch_final_cmd() -> str:
    return 'CMD ["/bin/sh", "-c", "python3 scripts/package_arch.py --out ./packaging/"]'


# ---- Distro targets ----------------------------------------------------------

DISTS = {
    "debian12": {"family": "deb", "image": "debian:12", "replace": {"@development-tools": ""}, "tpm": True},
    "debian13": {"family": "deb", "image": "debian:13", "replace": {"@development-tools": ""}, "tpm": True},
    "ubuntu22.04": {"family": "deb", "image": "ubuntu:22.04", "tpm": True},
    "ubuntu24.04": {"family": "deb", "image": "ubuntu:24.04", "tpm": True},
    "ubuntu25.10": {"family": "deb", "image": "ubuntu:25.10", "tpm": True},
    "ubuntu26.04": {"family": "deb", "image": "ubuntu:26.04", "tpm": True},
    "test": {"family": "deb", "image": "ubuntu:24.04", "tpm": False, "extra_pkgs": ["nodejs"]},
    "fedora43": {"family": "rpm", "image": "fedora:43", "tpm": True, "selinux": True},
    "fedora44": {"family": "rpm", "image": "fedora:44", "tpm": True, "selinux": True},
    "rawhide": {"family": "rpm", "image": "fedora:rawhide", "extra_prep": ["RUN dnf -y --refresh update glibc glibc-common glibc-minimal-langpack systemd-libs systemd-standalone-sysusers rpm-libs rpm && dnf -y --refresh update"], "tpm": True, "selinux": True},
    "rocky8": {"family": "rpm", "image": "rockylinux/rockylinux:8", "extra_prep": ["RUN dnf -y install 'dnf-command(config-manager)' && dnf config-manager --set-enabled powertools", "RUN dnf -y install python39 && alternatives --set python3 /usr/bin/python3.9"], "replace": {"build-essential": '"@Development Tools"', "@development-tools": ""}, "tpm": False, "selinux": True, "arm64": False},
    "rocky9": {"family": "rpm", "image": "rockylinux/rockylinux:9", "extra_prep": ["RUN dnf -y install 'dnf-command(config-manager)' && dnf config-manager --set-enabled crb", "RUN sed -i -e 's|$rltype||g' /etc/yum.repos.d/rocky*.repo"], "replace": {"build-essential": '"@Development Tools"', "@development-tools": "", "curl": ""}, "tpm": True, "selinux": True},
    "rocky10": {"family": "rpm", "image": "rockylinux/rockylinux:10", "extra_prep": ["RUN dnf install -y 'dnf-command(config-manager)' && dnf config-manager --set-enabled crb", "RUN sed -i -e 's|$rltype||g' /etc/yum.repos.d/rocky*.repo"], "replace": {"build-essential": '"@Development Tools"', "@development-tools": ""}, "tpm": True, "selinux": True},
    "sle15sp6": {"family": "zypper", "image": "registry.suse.com/suse/sle15:15.6", "scc": True, "scc_vers": "15.6", "post_bootstrap": ["RUN zypper --non-interactive install python311 && ln -sf /usr/bin/python3.11 /usr/bin/python3"], "replace": {"build-essential": "", "@development-tools": "", "dbus-devel": "dbus-1-devel", "tpm2-tss-devel": "tpm2-0-tss-devel", "sqlite-devel": "sqlite3-devel", "policycoreutils-devel": "", "selinux-policy-targeted": ""}, "tpm": True, "apparmor": True},
    "sle15sp7": {"family": "zypper", "image": "registry.suse.com/suse/sle15:15.7", "scc": True, "scc_vers": "15.7", "post_bootstrap": ["RUN zypper --non-interactive install python311 && ln -sf /usr/bin/python3.11 /usr/bin/python3"], "replace": {"build-essential": "", "@development-tools": "", "dbus-devel": "dbus-1-devel", "tpm2-tss-devel": "tpm2-0-tss-devel", "sqlite-devel": "sqlite3-devel", "clang": "clang7", "policycoreutils-devel": "", "selinux-policy-targeted": ""}, "tpm": True, "apparmor": True},
    "sle16": {"family": "zypper", "image": "registry.suse.com/bci/bci-sle16-kernel-module-devel:16.0", "scc": True, "scc_vers": "16.0", "extra_prep": ["RUN zypper in -y --oldpackage libudev1-257.7-160000.2.2.$(uname -m)", "RUN zypper ar -e https://download.opensuse.org/repositories/home:/dmulder:/branches:/authselect/16.0/home:dmulder:branches:authselect.repo", "RUN zypper --non-interactive --gpg-auto-import-keys refresh home_dmulder_branches_authselect"], "replace": {"build-essential": "", "@development-tools": "", "dbus-devel": "dbus-1-devel", "tpm2-tss-devel": "tpm2-0-tss-devel", "sqlite-devel": "sqlite3-devel", "selinux-policy-targeted": "selinux-tools selinux-policy-devel"}, "tpm": True, "selinux": True},
    "tumbleweed": {"family": "zypper", "image": "opensuse/tumbleweed:latest", "extra_prep": ["RUN zypper ar -e https://download.opensuse.org/repositories/security:/idm/openSUSE_Tumbleweed/security:idm.repo", "RUN zypper --non-interactive --gpg-auto-import-keys refresh security_idm"], "replace": {"build-effective": "", "@development-tools": "", "dbus-devel": "dbus-1-devel", "tpm2-tss-devel": "tpm2-0-tss-devel", "sqlite-devel": "sqlite3-devel", "selinux-policy-targeted": "selinux-tools selinux-policy-devel"}, "tpm": True, "selinux": True},
    "gentoo": {"family": "ebuild", "image": "python:3.11-slim", "extra_prep": [], "tpm": True, "selinux": False},
    "arch": {"family": "arch", "image": "archlinux:base-devel", "extra_prep": [], "tpm": True, "selinux": False},
    "amzn2023": {"family": "rpm", "image": "amazonlinux:2023", "extra_prep": [], "replace": {"build-essential": '"@Development Tools"', "@development-tools": "", "curl": ""}, "tpm": True, "selinux": True},
}

DOCKERFILE_TPL = """\
{GENERATED_MARKER}{tooling_stage}FROM --platform={docker_platform} {base_image}

{env}
{sle_connect}

ARG CARGO_PATCH_ARG=""

{bootstrap}
{post_bootstrap}
ENV PATH="/root/.cargo/bin:${{PATH}}"

VOLUME /himmelblau
WORKDIR /himmelblau

{rust_install}

{patch_libhimmelblau}

{selinux_enabled}
{final_cmd}
"""

DOCKERFILE_EBUILD_TPL = """\
{GENERATED_MARKER}FROM --platform={docker_platform} {base_image}

VOLUME /himmelblau
WORKDIR /himmelblau

{final_cmd}
"""

DOCKERFILE_CROSS_DEB_TPL = """\
{GENERATED_MARKER}FROM --platform=linux/amd64 {base_image}

{env}

ARG CARGO_PATCH_ARG=""

RUN dpkg --add-architecture arm64

{multiarch_sources}
{bootstrap}
{post_bootstrap}
RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-overwrite" \\
    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \\
    libssl-dev:arm64 \\
    libdbus-1-dev:arm64 \\
    libkrb5-dev:arm64 \\
    libpam0g-dev:arm64 \\
    libcap-dev:arm64 \\
    libudev-dev:arm64 \\
    libtss2-dev:arm64 \\
    libsqlite3-dev:arm64 \\
    libpcre2-dev:arm64 \\
    libunistring-dev:arm64 \\
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.cargo/bin:${{PATH}}"

VOLUME /himmelblau
WORKDIR /himmelblau

RUN --mount=type=cache,target=/root/.cargo/registry curl https://sh.rustup.rs -sSf | sh -s -- -y && echo 1.93.1 && \\
    rustup target add aarch64-unknown-linux-gnu && \\
    cargo install cargo-deb cargo-generate-rpm

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \\
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \\
    CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++ \\
    AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar \\
    PKG_CONFIG_PATH_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig \\
    PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu=/ \\
    PKG_CONFIG_ALLOW_CROSS=1

{patch_libhimmelblau}

{selinux_enabled}
{final_cmd}
"""

RUST_INSTALL_NATIVE = """\
RUN --mount=type=cache,target=/root/.cargo/registry curl https://sh.rustup.rs -sSf | sh -s -- -y && echo 1.93.1 && \\
    cargo install cargo-deb cargo-generate-rpm"""

RUST_INSTALL_EMULATED = """\
ENV CFLAGS="-O2" CXXFLAGS="-O2"
RUN --mount=type=cache,target=/root/.cargo/registry curl https://sh.rustup.rs -sSf | sh -s -- -y && echo 1.93.1 && \\
    cargo install cargo-deb cargo-generate-rpm"""

UBUNTU_CODENAMES = {"ubuntu:22.04": "jammy", "ubuntu:24.04": "noble", "ubuntu:25.10": "plucky", "ubuntu:26.04": "resolute"}
UBUNTU_DEB822_VERSIONS = {"ubuntu:24.04", "ubuntu:25.10", "ubuntu:26.04"}


def build_multiarch_sources(dist_cfg):
    image = dist_cfg["image"]
    if not image.startswith("ubuntu:"):
        return ""
    codename = UBUNTU_CODENAMES.get(image)
    if not codename:
        print(f"[WARNING] No codename in UBUNTU_CODENAMES for {image} — arm64 apt sources not configured!")
        return ""
    if image in UBUNTU_DEB822_VERSIONS:
        return f"""\
RUN sed -i '/^Types: deb$/a Architectures: amd64' /etc/apt/sources.list.d/ubuntu.sources
RUN cat <<'EOF' > /etc/apt/sources.list.d/ubuntu-arm64.sources
Types: deb
URIs: http://ports.ubuntu.com/ubuntu-ports/
Suites: {codename} {codename}-updates {codename}-backports
Components: main restricted universe multiverse
Architectures: arm64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://ports.ubuntu.com/ubuntu-ports/
Suites: {codename}-security
Components: main restricted universe multiverse
Architectures: arm64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF
"""
    return f"""\
RUN sed -i 's/^deb http/deb [arch=amd64] http/' /etc/apt/sources.list && \\
    echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ {codename} main restricted universe multiverse" >> /etc/apt/sources.list && \\
    echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ {codename}-updates main restricted universe multiverse" >> /etc/apt/sources.list && \\
    echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ {codename}-backports main restricted universe multiverse" >> /etc/apt/sources.list && \\
    echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ {codename}-security main restricted universe multiverse" >> /etc/apt/sources.list
"""


SLE_CONNECT_TPL = """\
RUN zypper --non-interactive refresh && \\
    zypper --non-interactive install --no-recommends \\
        SUSEConnect \\
        ca-certificates \\
        suse-build-key && \\
    zypper clean --all

RUN --mount=type=secret,id=scc_regcode,dst=/run/secrets/scc_regcode \\
    set -e && \\
    source /run/secrets/scc_regcode && \\
    SUSEConnect --email "$email" --regcode "$regcode" && \\
    SUSEConnect -p PackageHub/{scc_vers}/$(uname -m)
"""


def build_pkg_list(dist_cfg, selinux):
    fam = FAMILIES[dist_cfg["family"]]
    pkgs = list(fam["pkgs"])
    rep = dist_cfg.get("replace", {})
    out = []
    if selinux:
        pkgs += SELINUX_PKGS
    for p in pkgs:
        q = rep.get(p, p)
        if q:
            out.append(q)
    out.extend(dist_cfg.get("extra_pkgs", []))
    out = sorted(set(out))
    return " \\\n        ".join(out)


def render(dist_name, dist_cfg, patch_libhimmelblau, arch="amd64"):
    fam = FAMILIES[dist_cfg["family"]]
    selinux = bool(dist_cfg.get("selinux", False))
    pkgs = build_pkg_list(dist_cfg, selinux)
    bootstrap = fam["bootstrap"].format(pkgs=pkgs).rstrip() if "{pkgs}" in fam["bootstrap"] else fam["bootstrap"].rstrip()
    env = fam["env"] or ""
    sle_connect = SLE_CONNECT_TPL.format(scc_vers=dist_cfg.get("scc_vers")) if dist_cfg.get("scc") else ""

    features = ["tpm"] if dist_cfg.get("tpm", False) else []
    arch_info = ARCH_MAP.get(arch, ARCH_MAP["amd64"])
    cross_target = arch_info["rust_target"] if arch != "amd64" else ""

    if dist_cfg["family"] == "deb" and dist_name != "test":
        final_cmd = build_deb_final_cmd(features, dist_name, cross_target=cross_target)
    elif dist_name == "test":
        final_cmd = "CMD cargo test"
    elif dist_cfg["family"] == "ebuild":
        final_cmd = build_gentoo_final_cmd(features, Path(__file__).parent.parent.resolve())
    elif dist_cfg["family"] == "arch":
        final_cmd = build_arch_final_cmd()
    else:
        final_cmd = build_rpm_final_cmd(features, selinux, bool(dist_cfg.get("apparmor", False)))

    extra = "\n".join(dist_cfg.get("extra_prep", []))
    extra = extra + ("\n" if extra else "")
    post_bootstrap = "\n".join(dist_cfg.get("post_bootstrap", []))
    post_bootstrap = post_bootstrap + ("\n" if post_bootstrap else "")

    if arch != "amd64" and dist_cfg["family"] == "deb":
        return DOCKERFILE_CROSS_DEB_TPL.format(
            GENERATED_MARKER=GENERATED_MARKER,
            base_image=dist_cfg["image"],
            env=env,
            multiarch_sources=build_multiarch_sources(dist_cfg),
            bootstrap=(extra + bootstrap),
            post_bootstrap=post_bootstrap,
            selinux_enabled=("ENV HIMMELBLAU_ALLOW_MISSING_SELINUX=1" if not selinux else ""),
            patch_libhimmelblau="COPY ./scripts/cargo-patch-config.toml /root/.cargo/config.toml" if patch_libhimmelblau else "",
            final_cmd=final_cmd,
        )

    if dist_cfg["family"] == "arch":
        rust_install = ""
        tooling_stage = ""
    elif arch != "amd64":
        rust_install = RUST_INSTALL_EMULATED
        tooling_stage = ""
    else:
        rust_install = RUST_INSTALL_NATIVE
        tooling_stage = ""

    if dist_cfg["family"] == "ebuild":
        return DOCKERFILE_EBUILD_TPL.format(
            GENERATED_MARKER=GENERATED_MARKER,
            docker_platform=arch_info["docker_platform"],
            base_image=dist_cfg["image"],
            final_cmd=final_cmd,
        )

    return DOCKERFILE_TPL.format(
        GENERATED_MARKER=GENERATED_MARKER,
        tooling_stage=tooling_stage,
        docker_platform=arch_info["docker_platform"],
        base_image=dist_cfg["image"],
        env=env,
        bootstrap=(extra + bootstrap),
        post_bootstrap=post_bootstrap,
        sle_connect=("\n" + sle_connect + "\n" if sle_connect else ""),
        rust_install=rust_install,
        selinux_enabled=("ENV HIMMELBLAU_ALLOW_MISSING_SELINUX=1" if not selinux else ""),
        patch_libhimmelblau="COPY ./scripts/cargo-patch-config.toml /root/.cargo/config.toml" if patch_libhimmelblau else "",
        final_cmd=final_cmd,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="./dockerfiles", help="Output directory")
    ap.add_argument("--only", default="", help="Comma-separated list of dists to render")
    ap.add_argument("--arch", default="amd64", choices=sorted(ARCH_MAP.keys()), help="Target architecture (default: amd64)")
    ap.add_argument("--patch-libhimmelblau", dest="patch_libhimmelblau", action="store_true", help="Patch libhimmelblau with a local copy mounted at /libhimmelblau")
    ap.add_argument("--no-patch-libhimmelblau", dest="patch_libhimmelblau", action="store_false", help=argparse.SUPPRESS)
    ap.set_defaults(patch_libhimmelblau=False)
    args = ap.parse_args()

    want = {x.strip() for x in args.only.split(",") if x.strip()} if args.only else set(DISTS.keys())
    os.makedirs(args.out, exist_ok=True)
    arch_suffix = f".{args.arch}" if args.arch != "amd64" else ""

    written = []
    skipped = []
    for name in sorted(want):
        if name not in DISTS:
            print(f"[skip] unknown dist: {name}")
            continue
        if args.arch != "amd64" and not DISTS[name].get(args.arch, True):
            skipped.append(name)
            continue
        df = render(name, DISTS[name], args.patch_libhimmelblau, arch=args.arch)
        path = os.path.join(args.out, f"Dockerfile.{name}{arch_suffix}")
        with open(path, "w", encoding="utf-8") as f:
            f.write(df)
        written.append(path)

    print(f"Wrote {len(written)} Dockerfiles (arch={args.arch}):")
    for p in written:
        print("  -", p)
    if skipped:
        print(f"Skipped {len(skipped)} distros (no {args.arch} support): {', '.join(skipped)}")


if __name__ == "__main__":
    main()
