"""Check NixOS systemd units against generated units and intentional differences.

This test can be run to ensure that the NixOS systemd service files are up to
date with the service files generated by gen_servicefiles.py for other distros.

Evaluate the NixOS module without building or installing packages, then compare
its unit definitions with isolated output from gen_servicefiles.py. Cover socket
activation, FD-store settings, task hardening and dependencies, runtime paths,
policy cache tmpfiles rules, HSM PIN initialization, and TPM variants. These are
definition tests, not runtime integration tests.

The required nix/tests/services.nix fixture supplies the module evaluation and
test package placeholders; it is not a runtime or VM test.

Runtime paths, directory defaults, and the tasks service's umask/address-family
defaults follow the generated units. The HSM initializer retains the generator's
condition that skips initialization when an encrypted PIN already exists.
The policy cache tmpfiles rule is written literally in the NixOS module and
checked for exact equivalence with src/daemon/src/himmelblau-policies.tmpfiles.conf,
including detection of duplicate or conflicting rules for the same path.

Known deviations from the generated units and their rationale:
- Supported NixOS releases provide the required systemd features, so omit the
  generator's version gates for encrypted credentials and FD-store preservation.
- Gate HSM initialization, its dependencies, and encrypted credential loading on
  config.security.tpm2.enable, not on whether the daemon needs local TPM devices;
  they remain enabled for remote TCTIs when config.security.tpm2.enable is true.
- Include NixOS's tpm2-udev-trigger.service in both After and Wants on the HSM
  initializer, following the dependency pattern used by NixOS's tpm2-abrmd
  service to handle TPM udev-rule changes during rebuild activation.
- Keep NixOS's nscd/nsncd NSS proxy running; do not add Conflicts=nscd.service.
- Keep the daemon's Type=notify because it does not implement notify-reload.
- Retain the tasks service's BindsTo dependency instead of Requires, while
  ordering it after the daemon.
- Use configurable Nix package/configuration paths and Nix-provided tools,
  with additional network/time-service Wants and accounts-daemon/TPM-device
  startup dependencies.
- Retain conditional TPM device access, DeviceAllow, and the configured TPM
  group instead of the generator's default PrivateDevices=false and tss group.

Run with python3 scripts/test_nixos_services.py -v. Requires nix-instantiate and
a nixpkgs entry in NIX_PATH; tests are skipped if nix-instantiate is unavailable.
"""

import configparser
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def parse_unit(text):
    unit = configparser.ConfigParser(interpolation=None, strict=False)
    unit.optionxform = str
    unit.read_string(text)
    # systemd accumulates these list directives across repeated assignments.
    section = None
    lists = {}
    for line in text.splitlines():
        if line.startswith("["):
            section = line.strip("[]")
        elif "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            if key in {
                "After",
                "Before",
                "Requires",
                "BindsTo",
                "Wants",
                "Sockets",
                "CacheDirectory",
                "CapabilityBoundingSet",
                "AmbientCapabilities",
            }:
                lists.setdefault((section, key), []).extend(value.split())
    for (section, key), values in lists.items():
        unit[section][key] = " ".join(values)
    return unit


def evaluate(**args):
    command = [
        "nix-instantiate",
        "--eval",
        "--strict",
        "--json",
        "--arg",
        "nixpkgs",
        "<nixpkgs>",
        str(ROOT / "nix/tests/services.nix"),
    ]
    for name, value in args.items():
        command.extend(["--arg", name, json.dumps(value)])
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode:
        raise RuntimeError(f"Nix evaluation failed:\n{result.stderr}")
    return json.loads(result.stdout)


@unittest.skipUnless(
    shutil.which("nix-instantiate"), "Nix is required for module evaluation"
)
class NixosServiceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.evaluated = evaluate()
        cls.units = {
            name: parse_unit(text) for name, text in cls.evaluated["units"].items()
        }
        # The generator writes sockets relative to __file__, so isolate it too.
        cls.temp = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls.temp.cleanup)
        root = Path(cls.temp.name)
        scripts = root / "scripts"
        scripts.mkdir()
        generator = scripts / "gen_servicefiles.py"
        shutil.copyfile(ROOT / "scripts/gen_servicefiles.py", generator)
        subprocess.run(
            [
                sys.executable,
                str(generator),
                "--out-dir",
                str(root / "units"),
                "--assume-version",
                cls.evaluated["version"].split(".")[0],
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        cls.generated = {
            path.name: parse_unit(path.read_text())
            for directory in [root / "units", root / "platform/systemd"]
            for path in directory.iterdir()
        }

    def assert_directives_match(self, name, section, keys):
        actual = self.units[name][section]
        expected = self.generated[name][section]
        for key in keys:
            with self.subTest(unit=name, section=section, directive=key):
                self.assertEqual(actual[key], expected[key])

    def test_daemon_cache_and_restart_directives_match(self):
        self.assertEqual(self.units["himmelblaud.service"]["Service"]["Type"], "notify")
        self.assertFalse(
            [
                message
                for message in self.evaluated["assertions"]
                if message.startswith("services.himmelblau:")
            ]
        )
        self.assert_directives_match(
            "himmelblaud.service",
            "Service",
            [
                "User",
                "DynamicUser",
                "UMask",
                "CacheDirectory",
                "StateDirectory",
                "Restart",
                "RestartSec",
                "WatchdogSec",
                "FileDescriptorStoreMax",
                "FileDescriptorStorePreserve",
                "LoadCredentialEncrypted",
            ],
        )

    def test_hardening_matches_for_both_daemons(self):
        for name in ["himmelblaud.service", "himmelblaud-tasks.service"]:
            self.assert_directives_match(
                name,
                "Service",
                [
                    "NoNewPrivileges",
                    "PrivateTmp",
                    "PrivateDevices",
                    "ProtectSystem",
                    "ProtectHostname",
                    "ProtectClock",
                    "ProtectKernelTunables",
                    "ProtectKernelModules",
                    "ProtectKernelLogs",
                    "ProtectControlGroups",
                    "MemoryDenyWriteExecute",
                ],
            )

    def test_tasks_capabilities_cache_and_restart_directives_match(self):
        name = "himmelblaud-tasks.service"
        self.assert_directives_match(
            name,
            "Service",
            [
                "User",
                "Type",
                "Restart",
                "RestartSec",
                "WatchdogSec",
                "CapabilityBoundingSet",
                "AmbientCapabilities",
                "InaccessiblePaths",
                "CacheDirectory",
            ],
        )

    def test_directory_and_tasks_defaults_match_generated_units(self):
        for name, keys in [
            (
                "himmelblaud.service",
                ["RuntimeDirectory", "RuntimeDirectoryPreserve", "CacheDirectoryMode"],
            ),
            ("himmelblaud-tasks.service", ["UMask", "RestrictAddressFamilies"]),
        ]:
            for key in keys:
                with self.subTest(unit=name, directive=key):
                    self.assertEqual(
                        self.units[name]["Service"].get(key),
                        self.generated[name]["Service"].get(key),
                    )

    def test_policy_cache_tmpfiles_rules_match_packaged_file(self):
        rules = "\n".join(self.evaluated["tmpfilesRules"]).splitlines()
        source = ROOT / "src/daemon/src/himmelblau-policies.tmpfiles.conf"
        expected = [
            rule.strip()
            for rule in source.read_text().splitlines()
            if rule.strip() and not rule.lstrip().startswith("#")
        ]
        self.assertTrue(expected, "The packaged policy tmpfiles file must contain rules")
        paths = {rule.split()[1] for rule in expected}
        actual = [
            rule.strip()
            for rule in rules
            if not rule.lstrip().startswith("#")
            and len(rule.split()) >= 2
            and rule.split()[1] in paths
        ]
        self.assertEqual(actual, expected)

    def test_tasks_stay_bound_to_daemon(self):
        tasks = self.units["himmelblaud-tasks.service"]["Unit"]
        self.assertEqual(tasks["BindsTo"], "himmelblaud.service")
        self.assertIn("himmelblaud.service", tasks["After"].split())
        self.assertNotIn("Requires", tasks)

    def test_runtime_paths_match_generated_units(self):
        name = "himmelblaud-tasks.service"
        self.assert_directives_match(name, "Unit", ["ConditionPathExists"])
        self.assert_directives_match(name, "Service", ["ReadWritePaths"])

    def test_startup_dependencies_and_limits_match(self):
        for name in ["himmelblaud.service", "himmelblaud-tasks.service"]:
            actual = self.units[name]["Unit"]
            expected = self.generated[name]["Unit"]
            for key in ["After", "Before", "Requires", "Wants", "Upholds"]:
                if key in expected:
                    with self.subTest(unit=name, directive=key):
                        dependencies = set(actual.get(key, "").split())
                        if key == "Requires":
                            dependencies.update(actual.get("BindsTo", "").split())
                        self.assertLessEqual(set(expected[key].split()), dependencies)
            self.assertEqual(actual["StartLimitIntervalSec"].removesuffix("s"), "30")
            self.assertEqual(actual["StartLimitBurst"], "8")
        daemon = self.units["himmelblaud.service"]
        self.assertIn("accounts-daemon.service", daemon["Unit"]["Before"].split())
        self.assertIn("accounts-daemon.service", daemon["Install"]["WantedBy"].split())

    def test_nixos_nss_proxy_is_not_stopped(self):
        self.assertTrue(self.evaluated["nscdEnabled"])
        daemon = self.units["himmelblaud.service"]["Unit"]
        self.assertIn("nscd.service", daemon["After"].split())
        self.assertNotIn("nscd.service", daemon.get("Conflicts", "").split())

    def test_socket_activation_matches_without_early_boot_activation(self):
        sockets = []
        for name, expected in self.generated.items():
            if not name.endswith(".socket"):
                continue
            sockets.append(name)
            actual = self.units[name]
            self.assertEqual(dict(actual["Socket"]), dict(expected["Socket"]))
            self.assert_directives_match(name, "Unit", ["Before", "PartOf"])
            self.assertIn(actual["Unit"]["DefaultDependencies"], ["false", "no"])
            self.assertLessEqual(
                set(expected["Unit"]["After"].split()),
                set(actual["Unit"]["After"].split()),
            )
            self.assertNotIn("Install", actual)
        self.assertEqual(
            set(self.units["himmelblaud.service"]["Service"]["Sockets"].split()),
            set(sockets),
        )

    def test_hsm_initialization_matches_generator_with_nixos_udev(self):
        name = "himmelblau-hsm-pin-init.service"
        self.assert_directives_match(
            name,
            "Unit",
            ["Description", "Before", "ConditionPathExists"],
        )
        for key in ["After", "Wants"]:
            with self.subTest(directive=key):
                self.assertEqual(
                    set(self.units[name]["Unit"][key].split()),
                    set(self.generated[name]["Unit"][key].split())
                    | {"tpm2-udev-trigger.service"},
                )
        self.assertIn(self.units[name]["Unit"]["DefaultDependencies"], ["false", "no"])
        self.assertNotIn("RequiresMountsFor", self.units[name]["Unit"])
        self.assert_directives_match(name, "Service", ["Type"])
        self.assertTrue(
            self.units[name]["Service"]["ExecStart"].endswith(
                "/libexec/himmelblau-init-hsm-pin"
            )
        )
        self.assert_directives_match(name, "Install", ["WantedBy"])

    def test_tpm_disabled_and_remote_tcti_keep_device_isolation(self):
        for args in [
            {"tpmEnabled": False},
            {"tcti": "swtpm:host=127.0.0.1,port=2321"},
        ]:
            with self.subTest(args=args):
                evaluated = evaluate(**args)
                daemon = parse_unit(evaluated["units"]["himmelblaud.service"])
                self.assertEqual(daemon["Service"]["PrivateDevices"], "true")
                self.assertNotIn("DeviceAllow", daemon["Service"])
                self.assertNotIn("SupplementaryGroups", daemon["Service"])
                self.assertEqual(daemon["Service"]["FileDescriptorStoreMax"], "1")
                self.assertEqual(daemon["Service"]["FileDescriptorStorePreserve"], "yes")

    def test_hsm_initialization_uses_tpm_enablement_not_device_access(self):
        name = "himmelblau-hsm-pin-init.service"
        for args in [
            {"tpmEnabled": False},
            {"tpmEnabled": True},
            {"tpmEnabled": True, "tcti": "swtpm:host=127.0.0.1,port=2321"},
        ]:
            with self.subTest(args=args):
                enabled = args["tpmEnabled"]
                evaluated = evaluate(**args)
                daemon = parse_unit(evaluated["units"]["himmelblaud.service"])
                self.assertEqual(
                    "LoadCredentialEncrypted" in daemon["Service"], enabled
                )
                self.assertEqual(
                    "HIMMELBLAU_HSM_PIN_PATH=%d/hsm-pin"
                    in evaluated["units"]["himmelblaud.service"],
                    enabled,
                )
                self.assertEqual(name in evaluated["units"], enabled)
                for key in ["After", "Wants"]:
                    self.assertEqual(name in daemon["Unit"][key].split(), enabled)
                if enabled:
                    initializer = parse_unit(evaluated["units"][name])
                    for key in ["After", "Wants"]:
                        self.assertIn(
                            "tpm2-udev-trigger.service", initializer["Unit"][key].split()
                        )
                    self.assertEqual(
                        daemon["Service"]["LoadCredentialEncrypted"],
                        self.generated["himmelblaud.service"]["Service"][
                            "LoadCredentialEncrypted"
                        ],
                    )
                    self.assertIn(
                        "himmelblaud.service", initializer["Install"]["WantedBy"].split()
                    )
                for socket_name, text in evaluated["units"].items():
                    if socket_name.endswith(".socket"):
                        self.assertEqual(
                            name in parse_unit(text)["Unit"]["After"].split(), enabled
                        )

    def test_custom_tpm_group_is_retained(self):
        evaluated = evaluate(tssGroup="custom-tss")
        daemon = parse_unit(evaluated["units"]["himmelblaud.service"])
        self.assertEqual(daemon["Service"]["SupplementaryGroups"], "custom-tss")
        self.assertEqual(daemon["Service"]["DeviceAllow"], "char-tpm rw")

    def test_fd_store_settings_keep_notify_service(self):
        daemon = self.units["himmelblaud.service"]["Service"]
        self.assertEqual(daemon["Type"], "notify")
        self.assertEqual(daemon["FileDescriptorStoreMax"], "1")
        self.assertEqual(daemon["FileDescriptorStorePreserve"], "yes")


if __name__ == "__main__":
    unittest.main()
