#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    if command -v deb-systemd-helper >/dev/null 2>&1; then
        if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ]; then
            deb-systemd-invoke stop himmelblaud-orchestrator.service >/dev/null || true
        fi
    elif command -v systemctl >/dev/null 2>&1; then
        systemctl stop himmelblaud-orchestrator.service >/dev/null || true
    fi
fi
