# crate2nix action
#
# Check if the Cargo.nix is up-to-date and if not register the new one as artifact so contributors do not have to install nix
name: "crate2nix: Cargo.nix check"
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  crate2nix:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@cec65ff6f104850203b152861d3f9e5f1747885d

      - name: Generate Cargo.nix
        run: nix run nixpkgs#crate2nix -- generate

      - name: Check for modifications
        id: check
        run: git diff --quiet Cargo.nix || echo "modified=true" >> "$GITHUB_OUTPUT"

      - name: Upload updated Cargo.nix
        if: steps.check.outputs.modified == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: Cargo.nix
          archive: false

      - name: Fail if modified
        if: steps.check.outputs.modified == 'true'
        run: |
          echo "::error file=Cargo.nix::Cargo.nix is out of date. Please download the 'Cargo.nix' artifact from this run summary (or run 'crate2nix generate' locally) and commit the changes."
          exit 1
