---
# yamllint disable rule:line-length
name: Dependabot auto-approval and auto-merge
"on":
  pull_request:
    branches:
      - main
      - stable-0.1.x
      - stable-0.2.x
      - stable-0.3.x
      - stable-0.4.x
      - stable-0.5.x
      - stable-0.6.x
      - stable-0.7.x
      - stable-0.8.x
      - stable-0.9.x

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # limit this to PRs opened by dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          alert-lookup: true
          compat-lookup: true
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Approve a PR if not already approved
        run: scripts/dependabot_automerge_check.sh "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
