name: Append Footer Based on Issue Type
permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  append-footer:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Append footer
        uses: julien-deramond/update-issue-body@04d5de9497fa264075b0d91ba018a73ca5ae5654 # v1
        with:
          issue-number: ${{ github.event.issue.number }}
          edit-mode: append
          append-separator: newline
          body: |
            ---
        
            ### 💡 Help Make It Happen!
            
            Want to see this issue resolved faster? Fund its implementation through our **Backer's Bounty** program, where you choose which issues get priority!
            
            [![Donate to Our Collective](https://opencollective.com/himmelblau/donate/button.png?color=blue)](https://himmelblau-idm.org/backers.html#backers-bounty)
            
            For US tax exempt donations:
            
            [![Donate US Tax Exempt](https://www.spi-inc.org/images/paypal_btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8GYKFLX9UNCH2)
            
            Your support helps drive Himmelblau’s evolution!
