---
name: NixOS
permissions:
  contents: read

# Trigger the workflow only on push
on:
  push:
    branches:
      - stable-2.x
      - stable-3.x

jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      with:
        extra_nix_config: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: himmelblau
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: nix build --no-link --print-out-paths --max-jobs 1 ".#himmelblau" ".#himmelblau-desktop" | cachix push himmelblau
