---
name: NixOS
permissions:
  contents: read

# Trigger the workflow only on push
on:
  push:
    branches:
      - stable-2.x
      - stable-3.x

jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      with:
        extra_nix_config: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: himmelblau
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: nix build --no-link --print-out-paths --max-jobs 1 ".#himmelblau" ".#himmelblau-desktop" | cachix push himmelblau
