---
name: NixOS
permissions:
  contents: read

# Trigger the workflow only on push
on:
  push:
    branches:
      - stable-2.x
      - stable-3.x

jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      with:
        extra_nix_config: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: himmelblau
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: nix build --no-link --print-out-paths --max-jobs 1 ".#himmelblau" ".#himmelblau-desktop" | cachix push himmelblau
