---
name: NixOS-CI

# Trigger the workflow on push or pull request
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@3c034b51a9deec0a09ef1df8b436ac5db50fae94
      - run: nix flake check
      - run: nix build .#daemon .#sso .#broker .#pam .#nss .#aad-tool .#o365 2>&1
