name: Stale Checker
permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Stale Issue
        uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had recent activity. 
            If no further activity occurs, it will be closed in 7 days. 
            Thank you for your contributions!
          stale-pr-label: 'stale'
          days-before-stale: 60
          days-before-close: 7
          operations-per-run: 100
          exempt-draft-pr: true
          only-issue-types: 'Bug'
          exempt-issue-labels: 'stale exempt'
          exempt-pr-labels: 'stale exempt'
          exempt-all-pr-assignees: true
